In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# EDA Before Preprocessing

In [2]:
df1 = pd.read_csv(r"chennai house market data 1.csv")

In [3]:
df1.info

<bound method DataFrame.info of        price  area              status  bhk  bathroom  age     location  \
0      37.49   872       Ready to move    2       NaN  1.0    Sembakkam
1      93.54  1346  Under Construction    3       2.0  NaN     Selaiyur
2     151.00  2225  Under Construction    3       NaN  0.0    Mogappair
3      49.00  1028       Ready to move    2       2.0  3.0     Ambattur
4      42.28   588  Under Construction    2       1.0  0.0   Pallavaram
...      ...   ...                 ...  ...       ...  ...          ...
2615   27.50   750       Ready to move    2       2.0  3.0  Veppampattu
2616   27.50   750       Ready to move    2       2.0  3.0  Veppampattu
2617   30.00   800       Ready to move    2       2.0  3.0  Veppampattu
2618   31.50   850       Ready to move    2       2.0  3.0  Veppampattu
2619   34.00   900       Ready to move    2       2.0  3.0  Veppampattu

                                   builder
0                            MP Developers
1                            DAC Promoters
2        Casagrand Builder Private Limited
3                   Dugar Housing Builders
4     Radiance Realty Developers India Ltd
...                                    ...
2615              Velan Housing Properties
2616              Velan Housing Properties
2617              Velan Housing Properties
2618              Velan Housing Properties
2619              Velan Housing Properties

[2620 rows x 8 columns]>

In [4]:
df1.shape

(2620, 8)

In [5]:
df1.columns

Index(['price', 'area', 'status', 'bhk', 'bathroom', 'age', 'location',
       'builder'],
      dtype='str')

In [6]:
df1.dtypes

price       float64
area          int64
status          str
bhk           int64
bathroom    float64
age         float64
location        str
builder         str
dtype: object

In [7]:
df1.head(5)

,price,area,status,bhk,bathroom,age,location,builder
0,37.49,872,Ready to move,2,NaN,1.0,Sembakkam,MP Developers
1,93.54,1346,Under Construction,3,2.0,NaN,Selaiyur,DAC Promoters
2,151.00,2225,Under Construction,3,NaN,0.0,Mogappair,Casagrand Builder Private Limited
3,49.00,1028,Ready to move,2,2.0,3.0,Ambattur,Dugar Housing Builders
4,42.28,588,Under Construction,2,1.0,0.0,Pallavaram,Radiance Realty Developers India Ltd

In [8]:
df1.tail(5)

,price,area,status,bhk,bathroom,age,location,builder
2615,27.5,750,Ready to move,2,2.0,3.0,Veppampattu,Velan Housing Properties
2616,27.5,750,Ready to move,2,2.0,3.0,Veppampattu,Velan Housing Properties
2617,30.0,800,Ready to move,2,2.0,3.0,Veppampattu,Velan Housing Properties
2618,31.5,850,Ready to move,2,2.0,3.0,Veppampattu,Velan Housing Properties
2619,34.0,900,Ready to move,2,2.0,3.0,Veppampattu,Velan Housing Properties

In [9]:
df1.sample(5)

,price,area,status,bhk,bathroom,age,location,builder
1090,79.38,1575,Under Construction,3,2.0,0.0,Sholinganallur,Prestige Estates Projects Ltd
1811,64.60,1700,Under Construction,3,3.0,NaN,Thaiyur,Propsource Realty Private Limited
1108,72.00,1400,Ready to move,3,2.0,7.0,Thoraipakkam OMR,seller
2579,89.23,1373,Under Construction,3,NaN,0.0,Koyambedu,Luxclusive Homes
267,66.99,1155,Under Construction,3,NaN,0.0,Pammal,Asset Tree Homes

In [10]:
df1.isnull().sum()

price          0
area           0
status         0
bhk            0
bathroom    1217
age          891
location       0
builder        0
dtype: int64

In [11]:
df1.describe()

             price         area          bhk     bathroom          age
count  2620.000000  2620.000000  2620.000000  1403.000000  1729.000000
mean     93.834683  1282.925191     2.443893     2.359230     1.355119
std     113.609349   692.566319     0.811984     0.844951     2.102682
min      12.830000   300.000000     1.000000     1.000000     0.000000
25%      42.000000   877.000000     2.000000     2.000000     0.000000
50%      61.735000  1091.500000     2.000000     2.000000     0.000000
75%      90.000000  1471.250000     3.000000     3.000000     3.000000
max    1422.000000  6700.000000     8.000000     7.000000    32.000000

In [13]:
print(df1['builder'].unique())

<ArrowStringArray>
[                       'MP Developers',
                        'DAC Promoters',
    'Casagrand Builder Private Limited',
               'Dugar Housing Builders',
 'Radiance Realty Developers India Ltd',
             'Traventure Homes Pvt Ltd',
                            'Urbanrise',
       'Navin Housing Properties P LTD',
     'Jones foundation private limited',
                           'Isha Homes',
 ...
              'Chennai Gated Community',
                               'Balaji',
                            'MrPincode',
                           'GJ ESTATES',
                            'Venkatesh',
                        'DJ Properties',
                           'Dhivagaran',
                         'REALTY INDIA',
                  'MAXWORTH PROPERTIES',
             'Velan Housing Properties']
Length: 135, dtype: str

In [14]:
print(df1['location'].unique())

<ArrowStringArray>
[                   'Sembakkam',                     'Selaiyur',
                    'Mogappair',                     'Ambattur',
                   'Pallavaram',                'Virugambakkam',
                'Thirumazhisai',                   'Moolakadai',
                'Ottiyambakkam',                'Perungalathur',
 ...
                'Jafferkhanpet',                   'Arumbakkam',
                 'Kuthambakkam',                  'Thirumalpur',
          'Mahindra World City', 'Oragadam Industrial Corridor',
            'Ragavendra Colony',   'Ambattur INDUSTRIAL ESTATE',
                  'Mannivakkam',             'Kil Ayanambakkam']
Length: 178, dtype: str

In [15]:
max(df1['age'])

32.0