In [40]:
import pandas as pd
import numpy as np

In [41]:
df1 = pd.read_csv(r"chennai house market data 1.csv")

In [42]:
"""Replacing the missing values of bathroom with mean of number bathrooms in other houses of their locality"""

bathroom_means = df1.groupby("location")["bathroom"].mean()
df1.loc[df1["bathroom"].isna(), "bathroom"] = (
    df1.loc[df1["bathroom"].isna(), "location"].map(bathroom_means)
)

""" global fallback for locations with no Non-missing Value """
df1 = df1.fillna({"bathroom": df1["bathroom"].median()})

In [43]:
df1['bathroom'].isna().sum()

np.int64(0)

In [44]:
"""Replacing the missing values of age with mean of house age in their locality"""

age_means = df1.groupby("location")["age"].mean()
df1.loc[df1["age"].isna(), "age"] = (
    df1.loc[df1["age"].isna(), "location"].map(age_means)
)

""" global fallback for locations with no Non-missing Value """
df1 = df1.fillna({"age": df1["age"].median()})

In [45]:
df1['age'].isna().sum()

np.int64(0)

In [46]:
df1[["bathroom", 'age']]

      bathroom       age
0     2.022222  1.000000
1     2.000000  0.296296
2     2.142857  0.000000
3     2.000000  3.000000
4     1.000000  0.000000
...        ...       ...
2615  2.000000  3.000000
2616  2.000000  3.000000
2617  2.000000  3.000000
2618  2.000000  3.000000
2619  2.000000  3.000000

[2620 rows x 2 columns]

In [47]:
df1[['bathroom', 'age']].dtypes

bathroom    float64
age         float64
dtype: object

In [48]:
df1['bathroom'] = df1['bathroom'].astype('int64')
df1['age'] = df1['age'].astype('int64')

In [49]:
df1[['bathroom', 'age']].dtypes

bathroom    int64
age         int64
dtype: object

In [50]:
df1[["bathroom", 'age']]

      bathroom  age
0            2    1
1            2    0
2            2    0
3            2    3
4            1    0
...        ...  ...
2615         2    3
2616         2    3
2617         2    3
2618         2    3
2619         2    3

[2620 rows x 2 columns]

In [51]:
df1.to_csv(r"preprocessed_data_outliers_not_removed.csv", index=False)

In [52]:
# Outlier detection
df2 = df1.copy()
df2["price_per_sqft"] = df2["price"] / df2["area"]

# Remove extreme outliers using IQR
Q1 = df2["price_per_sqft"].quantile(0.25)
Q3 = df2["price_per_sqft"].quantile(0.75)
IQR = Q3 - Q1
df2 = df2[(df2["price_per_sqft"] >= Q1 - 1.5*IQR) & (df2["price_per_sqft"] <= Q3 + 1.5*IQR)]
df2 = df2.drop(columns=["price_per_sqft"])

In [53]:
df2.to_csv(r"preprocessed_data_outliers_removed.csv", index=False)

In [54]:
df1.shape

(2620, 8)

In [55]:
df2.shape

(2311, 8)